// Trusted resume-intelligence knowledge base seed documents.
// Each entry becomes 1+ chunks with metadata. Roles can be extended by
// appending entries — the RAG engine requires no changes for new roles.

export interface SeedDocument {
  title: string;
  category: 'resume_fundamentals' | 'ats' | 'resume_writing' | 'role_guidance';
  subcategory: string;
  role: string | null;
  source: string;
  version: string;
  content: string;
}

const V = 'v1';

export const KNOWLEDGE_SEED_DOCUMENTS: SeedDocument[] = [
  // ------------------------------------------------ Resume fundamentals
  {
    title: 'Resume Structure Essentials',
    category: 'resume_fundamentals',
    subcategory: 'resume_structure',
    role: null,
    source: 'resume_guidelines',
    version: V,
    content: `A strong resume follows a predictable structure: contact header, professional summary, skills, experience, projects, education, and certifications. Put the most relevant sections first for the target role. Keep the resume to one page for under 5 years of experience and at most two pages beyond that. Use a single-column layout with clear section headings so both recruiters and parsers read sections in order.`,
  },
  {
    title: 'Resume Section Best Practices',
    category: 'resume_fundamentals',
    subcategory: 'section_best_practices',
    role: null,
    source: 'resume_guidelines',
    version: V,
    content: `Every section must earn its place. The summary is 2-3 sentences tailored to the target role. Experience entries lead with role, company, dates, then 3-5 achievement bullets. Projects each state the problem, stack, and outcome with links. Education lists degree, field, institution, and graduation year. A standalone skills section groups tools by category such as languages, frameworks, databases, and cloud. Omit references, photos, and full street addresses.`,
  },
  {
    title: 'Professional Summary Guidelines',
    category: 'resume_fundamentals',
    subcategory: 'professional_summary',
    role: null,
    source: 'resume_guidelines',
    version: V,
    content: `An effective professional summary names the candidate's identity (for example "Backend engineer with 3 years building REST APIs"), 2-3 signature strengths backed by evidence later in the resume, and the target direction. Avoid generic claims like "hard-working team player" without proof. Mirror 2-3 key terms from the job description naturally. If the resume lacks a summary, the recruiter must infer positioning, which weakens alignment for both humans and keyword matching.`,
  },
  {
    title: 'Experience Section Guidelines',
    category: 'resume_fundamentals',
    subcategory: 'experience_section',
    role: null,
    source: 'resume_guidelines',
    version: V,
    content: `The experience section is the highest-signal part of most resumes. List roles in reverse chronological order with company, title, location, and dates. Each role carries 3-5 bullets starting with strong action verbs and ending with quantified outcomes where possible. Describe scope (team size, users, traffic), ownership (designed, led, shipped), and results (latency reduced, revenue influenced, defects cut). Unexplained gaps over 6 months should be addressed with freelancing, education, or projects.`,
  },
  {
    title: 'Project Section Guidelines',
    category: 'resume_fundamentals',
    subcategory: 'project_section',
    role: null,
    source: 'resume_guidelines',
    version: V,
    content: `Projects prove applied skill, especially for students and career switchers. Each project needs a name, one-line purpose, technology stack tags, 2-3 bullets on what was built and measured results, and a live or repository link. Prefer 2-4 substantial projects over many trivial ones. Full-stack or domain-relevant projects outweigh tutorial clones. Mention deployment, testing, and collaboration signals such as CI, code review, or team size.`,
  },
  {
    title: 'Education Section Guidelines',
    category: 'resume_fundamentals',
    subcategory: 'education_section',
    role: null,
    source: 'resume_guidelines',
    version: V,
    content: `Education entries include degree, field of study, institution, and graduation year. Recent graduates may add GPA above 3.5, relevant coursework, and academic honors. Experienced candidates keep education brief at the bottom. Match the job's degree expectations explicitly: if the posting asks for a Bachelor's in Computer Science or related field, state the equivalent plainly. Bootcamps and online specializations belong under education or certifications, not as degree equivalents.`,
  },
  {
    title: 'Skills Section Guidelines',
    category: 'resume_fundamentals',
    subcategory: 'skills_section',
    role: null,
    source: 'resume_guidelines',
    version: V,
    content: `Group skills by category so scanners and readers map them fast: languages, frameworks, databases, cloud and DevOps, testing, and tools. List only skills usable in an interview; padding invites rejection. Mirror the job description's terminology (PostgreSQL rather than only "SQL databases") while keeping truthful. Keep the section scannable at 10-20 items; a wall of 40 keywords reads as stuffing and dilutes real strengths.`,
  },
  {
    title: 'Certification Guidelines',
    category: 'resume_fundamentals',
    subcategory: 'certifications',
    role: null,
    source: 'resume_guidelines',
    version: V,
    content: `Certifications help for cloud, security, and data roles when they match the job. Each entry states the exact certification name, issuer, and year. Prioritize current, verifiable credentials such as AWS Certified Solutions Architect, CKA, Security+, or relevant vendor certs. Expired or unrelated certificates add noise. Never invent credentials; background checks verify them and fabrication ends candidacies.`,
  },
  // ------------------------------------------------ ATS
  {
    title: 'ATS Parsing Principles',
    category: 'ats',
    subcategory: 'ats_parsing',
    role: null,
    source: 'ats_guidelines',
    version: V,
    content: `Applicant tracking systems extract raw text before any human reads the resume. They rely on standard section headings, simple single-column layouts, common fonts, and real text rather than images or text inside graphics. Tables, text boxes, headers and footers, icons for skills, and unusual characters frequently parse incorrectly. A resume that fails parsing loses keyword matches it actually deserved. Test by copying text out of the exported PDF and checking that sections, bullets, and contact details survive intact.`,
  },
  {
    title: 'Keyword Optimization',
    category: 'ats',
    subcategory: 'keyword_optimization',
    role: null,
    source: 'ats_guidelines',
    version: V,
    content: `ATS scoring rewards resumes that contain the job's required skills, tools, and domain phrases in context. Place keywords where they are earned: skills section for inventory, experience and project bullets for proof of use. Use the exact job-description spelling alongside common variants once (for example "Kubernetes (K8s)"). Missing required skills are the fastest way to lose points, so genuine matches must be spelled out rather than assumed. Never list skills without real experience.`,
  },
  {
    title: 'Resume Readability for ATS and Humans',
    category: 'ats',
    subcategory: 'readability',
    role: null,
    source: 'ats_guidelines',
    version: V,
    content: `Readable resumes serve two audiences: parsers and six-second skims. Use standard headings like Summary, Skills, Experience, Projects, Education. Keep bullet lines under roughly two lines, left-aligned, with consistent date formats. Avoid keyword stuffing, which both ATS heuristics and recruiters penalize. One clear claim per bullet with a verb, scope, and outcome beats dense paragraphs.`,
  },
  {
    title: 'ATS-Friendly Formatting',
    category: 'ats',
    subcategory: 'ats_formatting',
    role: null,
    source: 'ats_guidelines',
    version: V,
    content: `ATS-friendly formatting means standard fonts, 10-12pt body text, generous margins, simple bullet characters, and no multi-column layouts. Save and submit as a text-based PDF unless the posting requests otherwise. Avoid images, charts, logos, and skill proficiency bars, which parsers cannot read. Hyperlinks for portfolio, GitHub, and LinkedIn should be plain text URLs alongside descriptive labels so contact and proof links survive extraction.`,
  },
  {
    title: 'Section Naming Conventions',
    category: 'ats',
    subcategory: 'section_naming',
    role: null,
    source: 'ats_guidelines',
    version: V,
    content: `Use conventional section names so parsers classify content correctly: Professional Summary, Skills, Work Experience, Projects, Education, Certifications. Creative headings like "My Journey" or "Toolbox" are frequently misclassified and their keywords orphaned. Keep each section's content under its own heading rather than merging distinct topics. Contact details belong in the body header, not in PDF headers or footers which parsers often drop.`,
  },
  {
    title: 'Keyword Placement Strategy',
    category: 'ats',
    subcategory: 'keyword_placement',
    role: null,
    source: 'ats_guidelines',
    version: V,
    content: `Keyword placement matters as much as keyword presence. A skill named only once in a dense list scores less than one demonstrated in context. Repeat priority job skills up to 2-3 times across summary, skills, and a bullet proving usage. Place the highest-priority required skills in the top half of the first page. Align phrasing with the posting: if it says "CI/CD with GitHub Actions", that exact phrase should appear where the experience genuinely supports it.`,
  },
  {
    title: 'Job-Description Alignment',
    category: 'ats',
    subcategory: 'job_alignment',
    role: null,
    source: 'ats_guidelines',
    version: V,
    content: `Alignment means translating the job description into resume evidence. Map each required skill and responsibility to a concrete resume location: a skill tag plus a bullet proving use. Responsibilities with low textual overlap are usually the reason match scores stall even when skills match. Add specific examples using the employer's vocabulary for each unmatched responsibility that is truthful. Tailor the summary and top bullets per application instead of sending one generic resume everywhere.`,
  },
  // ------------------------------------------------ Resume writing
  {
    title: 'Strong Action Verbs',
    category: 'resume_writing',
    subcategory: 'action_verbs',
    role: null,
    source: 'writing_guidelines',
    version: V,
    content: `Start every bullet with a precise action verb that conveys ownership: built, designed, shipped, automated, optimized, led, migrated, hardened. Avoid weak openers like "worked on", "helped with", or "responsible for". Vary verbs across bullets so each contribution sounds distinct. Technical verbs should match the work: implemented for features, orchestrated for infrastructure, profiled and tuned for performance efforts.`,
  },
  {
    title: 'Achievement-Oriented Bullets',
    category: 'resume_writing',
    subcategory: 'achievement_bullets',
    role: null,
    source: 'writing_guidelines',
    version: V,
    content: `Achievement-oriented bullets answer three questions: what was done, how, and what changed. "Built REST APIs using Node.js and Express" states activity but no achievement. Stronger: "Built REST APIs with Node.js and Express serving 20k daily requests, cutting p95 latency 35% through caching and query tuning." Every bullet should carry scope or outcome: users, requests, latency, revenue, cost, defects, or team leverage. Bullets without any measurable impact read as responsibilities, not achievements.`,
  },
  {
    title: 'STAR-Style Bullet Construction',
    category: 'resume_writing',
    subcategory: 'star_bullets',
    role: null,
    source: 'writing_guidelines',
    version: V,
    content: `Use compressed STAR inside each bullet: Situation and Task in a short context clause, Action as the verb phrase, Result as the quantified outcome. Example: "Migrated session storage from in-memory to Redis (action) to fix peak-hour crashes (situation), eliminating outage incidents across two release cycles (result)." One to two lines per bullet keeps density high. Cut background detail that does not explain the scale or difficulty of the result.`,
  },
  {
    title: 'Quantification Guidelines',
    category: 'resume_writing',
    subcategory: 'quantification',
    role: null,
    source: 'writing_guidelines',
    version: V,
    content: `Quantify impact with real numbers only: percentages with baselines, absolute volumes, time saved, money moved, or scale handled. Good: "Reduced CI pipeline time from 25 to 9 minutes." Weak: "Improved CI significantly." Never invent metrics; if no measurement exists, state scope instead ("serving 3 services", "used by a 12-person team") or say that measurable impact is not currently present. Fabricated numbers are a serious integrity failure.`,
  },
  {
    title: 'Concise Writing and Removing Filler',
    category: 'resume_writing',
    subcategory: 'concise_writing',
    role: null,
    source: 'writing_guidelines',
    version: V,
    content: `Cut filler phrases: "responsible for", "various", "multiple", "assisted in", "leveraged synergies". Replace "Responsible for maintaining CI pipelines" with "Maintained CI pipelines cutting build failures 40%." Remove first-person pronouns and articles where safe. Each bullet should survive the deletion test: removing any single phrase must lose meaning. Shorter resumes with dense claims outperform longer ones padded with duties.`,
  },
  {
    title: 'Avoiding Generic Statements',
    category: 'resume_writing',
    subcategory: 'avoid_generic',
    role: null,
    source: 'writing_guidelines',
    version: V,
    content: `Generic statements like "fast learner", "passionate developer", or "detail-oriented professional" carry no signal because anyone can claim them. Replace traits with evidence: instead of "great communicator", write "Wrote runbooks adopted by 4 teams; onboarded 3 engineers." If a summary claims a strength, the body must prove it within one page. Unexplained adjectives are the most common weakness in junior resumes.`,
  },
  {
    title: 'Avoiding Keyword Stuffing',
    category: 'resume_writing',
    subcategory: 'avoid_stuffing',
    role: null,
    source: 'writing_guidelines',
    version: V,
    content: `Keyword stuffing means listing skills without evidence or repeating terms unnaturally. Both ATS heuristics and technical reviewers discount it. Every claimed skill should appear alongside proof: a project, role bullet, or certification. Prefer fewer, proven skills over long inventories. If a job skill is genuinely missing, say so in the gap analysis and suggest learning paths rather than pretending coverage.`,
  },
  {
    title: 'Bullet Quality Diagnostics',
    category: 'resume_writing',
    subcategory: 'bullet_quality',
    role: null,
    source: 'writing_guidelines',
    version: V,
    content: `Diagnose bullets on four axes: verb strength, technical specificity, scope, and outcome. A bullet like "Worked on backend" fails all four. A strong bullet names the system, the candidate's action, the technologies, and the measured effect. Flag passive voice, missing subjects, acronym soup without explanation, and results without baselines. Suggest a concrete rewrite that preserves only facts present in the original resume.`,
  },
  // ------------------------------------------------ Role guidance (14 roles)
  {
    title: 'Software Engineer Resume Guidance',
    category: 'role_guidance',
    subcategory: 'role_expectations',
    role: 'software_engineer',
    source: 'role_guidelines',
    version: V,
    content: `Software engineer resumes are judged on CS fundamentals, code ownership, and shipped impact. Expected signals: Git, data structures and algorithms, SQL, REST APIs, and unit testing. Show design decisions, testing discipline, and production debugging, not just feature lists. Include system scale and reliability outcomes. Missing fundamentals read as the largest gap for this role.`,
  },
  {
    title: 'Frontend Developer Resume Guidance',
    category: 'role_guidance',
    subcategory: 'role_expectations',
    role: 'frontend_developer',
    source: 'role_guidelines',
    version: V,
    content: `Frontend resumes must show JavaScript and TypeScript depth, React or equivalent framework work, semantic HTML and CSS, and web performance awareness. Strong bullets cite Core Web Vitals improvements, accessibility fixes, state-management design, and component reuse. Portfolio and deployed links matter more here than in most roles. Missing TypeScript, testing, or performance evidence are common weaknesses.`,
  },
  {
    title: 'Backend Developer Resume Guidance',
    category: 'role_guidance',
    subcategory: 'role_expectations',
    role: 'backend_developer',
    source: 'role_guidelines',
    version: V,
    content: `Backend resumes are evaluated on API development, data modeling, and operational robustness. Expected: Node.js or Python or Java, SQL and PostgreSQL, REST API design, Docker, and Git. Strong evidence includes endpoint design, auth, caching, migrations, background jobs, and latency or throughput numbers. Bullets like "Built REST APIs using Node.js and Express" need scope and impact: request volume, p95 latency, error budgets, or scale handled. Missing Docker, tests, or observability are frequent gaps.`,
  },
  {
    title: 'Full Stack Developer Resume Guidance',
    category: 'role_guidance',
    subcategory: 'role_expectations',
    role: 'full_stack_developer',
    source: 'role_guidelines',
    version: V,
    content: `Full stack resumes must prove breadth with depth in at least one layer: JavaScript, React, Node.js, Express, HTML and CSS, databases, and Git. Show end-to-end ownership: designed schema, built API, shipped UI, deployed with Docker or CI. Projects demonstrating the full loop outweigh isolated frontend or backend snippets. Common weakness: claiming many stacks with no deployed proof. Surface Docker and database experience explicitly when the job emphasizes containerized deployment.`,
  },
  {
    title: 'Data Analyst Resume Guidance',
    category: 'role_guidance',
    subcategory: 'role_expectations',
    role: 'data_analyst',
    source: 'role_guidelines',
    version: V,
    content: `Data analyst resumes hinge on SQL fluency, dashboarding, and business influence. Expected: SQL, Excel or Sheets, a BI tool such as Power BI or Tableau, and Python for analysis. Strong bullets tie analysis to decisions: "Built churn dashboard adopted by support leadership, cutting escalation analysis time 60%." Show data validation, stakeholder communication, and A/B or cohort reasoning. Missing business outcomes is the typical weakness.`,
  },
  {
    title: 'Data Scientist Resume Guidance',
    category: 'role_guidance',
    subcategory: 'role_expectations',
    role: 'data_scientist',
    source: 'role_guidelines',
    version: V,
    content: `Data science resumes need statistical rigor plus deployed modeling. Expected: Python, SQL, statistics, scikit-learn, and experiment design. Strong bullets state the business problem, features and models tried, offline and online metrics with baselines, and production status. "Trained an XGBoost model" is incomplete without precision, recall, lift, or revenue effect and without validation discipline. Missing experiment design or metric reasoning is a red flag.`,
  },
  {
    title: 'Machine Learning Engineer Resume Guidance',
    category: 'role_guidance',
    subcategory: 'role_expectations',
    role: 'machine_learning_engineer',
    source: 'role_guidelines',
    version: V,
    content: `ML engineer resumes bridge modeling and systems: training pipelines, serving, and monitoring. Expected: Python, PyTorch or TensorFlow, Docker, and cloud deployment basics. Strong evidence: data versioning, evaluation harnesses, latency and cost trade-offs, feature stores, and rollback or shadow-deployment practice. Pure notebook projects without serving or monitoring details underperform. Quantify inference latency, throughput, and model quality deltas.`,
  },
  {
    title: 'AI Engineer Resume Guidance',
    category: 'role_guidance',
    subcategory: 'role_expectations',
    role: 'ai_engineer',
    source: 'role_guidelines',
    version: V,
    content: `AI engineer resumes focus on LLM application engineering: retrieval-augmented generation, agent tooling, evaluation, and cost control. Expected: prompt design, embeddings and vector search, API integration, and guardrails. Strong bullets describe retrieval quality metrics, hallucination controls, latency and token-cost optimization, and human evaluation loops. Claims about model capabilities need measured evals, not adjectives. Missing evaluation or safety discussion is a common gap.`,
  },
  {
    title: 'DevOps Engineer Resume Guidance',
    category: 'role_guidance',
    subcategory: 'role_expectations',
    role: 'devops_engineer',
    source: 'role_guidelines',
    version: V,
    content: `DevOps resumes prove reliability engineering: Docker, Kubernetes, CI/CD, AWS, Linux, Terraform, and Git. Strong bullets quantify deployment frequency, lead time, change failure rate, and MTTR improvements. Show infrastructure-as-code ownership, observability stacks, and incident response. Tool lists without reliability outcomes read as shallow. Missing on-call, rollback, or cost-optimization evidence weakens seniority claims.`,
  },
  {
    title: 'Cloud Engineer Resume Guidance',
    category: 'role_guidance',
    subcategory: 'role_expectations',
    role: 'cloud_engineer',
    source: 'role_guidelines',
    version: V,
    content: `Cloud engineer resumes center on designing and operating workloads on AWS, Azure, or GCP: networking, IAM, compute, storage, and managed databases. Strong bullets show architecture choices, security hardening, high-availability design, and cost optimization with numbers. Certifications matching the target cloud help but never substitute for outage, migration, or scaling stories. Missing security or cost awareness is a frequent weakness.`,
  },
  {
    title: 'Product Manager Resume Guidance',
    category: 'role_guidance',
    subcategory: 'role_expectations',
    role: 'product_manager',
    source: 'role_guidelines',
    version: V,
    content: `Product manager resumes are judged on outcomes, not output: activation, retention, revenue, or efficiency moved through prioritization and cross-functional leadership. Strong bullets name the customer problem, the bet, the shipped scope, and the measured result with baselines. Show discovery craft: interviews, analytics, experiments. Roadmaps without results, or engineering-heavy skill lists without product outcomes, miss the role's bar.`,
  },
  {
    title: 'UI/UX Designer Resume Guidance',
    category: 'role_guidance',
    subcategory: 'role_expectations',
    role: 'ui_ux_designer',
    source: 'role_guidelines',
    version: V,
    content: `UI/UX resumes live on portfolio proof: research, flows, prototypes, and shipped interfaces with usability outcomes. Expected: Figma, interaction design, design systems, usability testing, and accessibility knowledge. Strong case studies state the user problem, iterations tested, and task-success or satisfaction deltas. Visual-only portfolios without research or metrics underperform. Missing accessibility or design-system contributions are common gaps.`,
  },
  {
    title: 'Cybersecurity Engineer Resume Guidance',
    category: 'role_guidance',
    subcategory: 'role_expectations',
    role: 'cybersecurity_engineer',
    source: 'role_guidelines',
    version: V,
    content: `Cybersecurity resumes must show threat modeling, detection, and response with concrete tooling: SIEM, networking, Linux, scripting, and cloud security basics. Strong bullets describe incidents handled, vulnerabilities remediated, detections authored with false-positive rates, or compliance frameworks satisfied. Certifications like Security+ or platform-specific credentials support but never replace incident stories. Vague "security best practices" claims without tooling or outcomes are the main weakness.`,
  },
  {
    title: 'Evaluating Experience Against Job Requirements',
    category: 'role_guidance',
    subcategory: 'experience_evaluation',
    role: null,
    source: 'role_guidelines',
    version: V,
    content: `When evaluating experience against a job requirement, map each requirement to explicit resume evidence: role titles, bullets, project tech, or years. Distinguish proven use (skill plus contextual bullet) from mere mention (skill listed without proof). Flag seniority mismatches where required years exceed detected years, and note where projects or internships partially offset gaps. Never infer experience the resume does not state; mark absent evidence as absent.`,
  },
];
