import PDFDocument from 'pdfkit';
import type { ResumeDetailResponse } from './resume.types.js';
import type { JobMatchAnalysis } from '../../ai/job/job-types.js';

export class ResumeReportExportService {
  async generateReportPdf(
    resume: ResumeDetailResponse,
    analysis?: JobMatchAnalysis | null,
  ): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 40, bottom: 40, left: 45, right: 45 },
        info: {
          Title: `Resume Analysis Report - ${resume.originalFilename}`,
          Author: 'Rework CV',
          Subject: 'ATS Resume Analysis Report',
        },
      });

      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', (err: Error) => reject(err));

      // Header Banner
      doc.font('Helvetica-Bold').fontSize(20).fillColor('#114B3E').text('Rework CV • Resume Intelligence Report');
      doc.moveDown(0.3);
      doc.font('Helvetica').fontSize(10).fillColor('#64748B').text(`Evaluation for: ${resume.originalFilename} | Date: ${new Date().toLocaleDateString()}`);
      doc.moveDown(1);

      // Score Section
      const score = analysis?.matchScore ?? resume.score ?? 0;
      doc.rect(45, doc.y, 505, 55).fillAndStroke('#F0FDF4', '#86EFAC');
      const boxY = doc.y - 55;
      doc.font('Helvetica-Bold').fontSize(22).fillColor('#16A36A').text(`${score}/100`, 60, boxY + 12);
      doc.font('Helvetica-Bold').fontSize(12).fillColor('#114B3E').text(`ATS Readiness & Job-Match Score - ${analysis?.category || 'Evaluated'}`, 150, boxY + 14);
      doc.font('Helvetica').fontSize(9).fillColor('#475569').text('Based on NER skill parsing, requirement alignment, and ATS format criteria.', 150, boxY + 30);
      doc.y = boxY + 70;

      // Overview
      if (analysis?.overview) {
        doc.font('Helvetica-Bold').fontSize(12).fillColor('#114B3E').text('Overview');
        doc.moveDown(0.4);
        doc.font('Helvetica').fontSize(9.5).fillColor('#334155').text(analysis.overview, { lineGap: 3 });
        doc.moveDown(1);
      }

      // Strengths / Highlights
      if (analysis?.strengths && analysis.strengths.length > 0) {
        doc.font('Helvetica-Bold').fontSize(12).fillColor('#166534').text('Key Strengths & Highlights');
        doc.moveDown(0.4);
        doc.font('Helvetica').fontSize(9).fillColor('#1E293B');
        for (const s of analysis.strengths) {
          doc.text(`• ${s}`, { lineGap: 2 });
        }
        doc.moveDown(1);
      }

      // Recommendations / Improvements
      if (analysis?.recommendations && analysis.recommendations.length > 0) {
        doc.font('Helvetica-Bold').fontSize(12).fillColor('#B45309').text('Actionable Improvements');
        doc.moveDown(0.4);
        doc.font('Helvetica').fontSize(9).fillColor('#1E293B');
        for (const r of analysis.recommendations) {
          doc.text(`[${r.priority.toUpperCase()}] ${r.text}`, { lineGap: 2 });
          if (r.impact) {
            doc.font('Helvetica-Oblique').fillColor('#64748B').text(`   Impact: ${r.impact}`, { lineGap: 2 }).font('Helvetica').fillColor('#1E293B');
          }
        }
        doc.moveDown(1);
      }

      // Skills Breakdown
      if (analysis?.matchedSkills?.length || analysis?.missingRequiredSkills?.length) {
        doc.font('Helvetica-Bold').fontSize(12).fillColor('#114B3E').text('Skills Assessment');
        doc.moveDown(0.4);
        if (analysis.matchedSkills?.length) {
          doc.font('Helvetica-Bold').fontSize(9).fillColor('#166534').text('Matched Skills:');
          doc.font('Helvetica').fontSize(8.5).fillColor('#334155').text(analysis.matchedSkills.join(', '));
          doc.moveDown(0.5);
        }
        if (analysis.missingRequiredSkills?.length) {
          doc.font('Helvetica-Bold').fontSize(9).fillColor('#DC2626').text('Missing Required Skills:');
          doc.font('Helvetica').fontSize(8.5).fillColor('#334155').text(analysis.missingRequiredSkills.join(', '));
          doc.moveDown(0.5);
        }
      }

      // Footer
      doc.fontSize(8).fillColor('#94A3B8').text(
        'Generated by Rework CV AI Platform — Confidential Career Report',
        45,
        780,
        { align: 'center', width: 505 },
      );

      doc.end();
    });
  }
}

export const resumeReportExportService = new ResumeReportExportService();
